---
- hosts: "all"
  become: true
  vars:
    nginx_listen_port: 8080
  tasks:
  - name: "Install nginx"
    ansible.builtin.apt:
      name: "nginx"
      state: "latest"
      update_cache: true
- template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
- tags: nginx-configuration
 handlers:
   - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes
   - name: reload nginx
    systemd:
    name: nginx
    state: reloaded